# Generated by Django 2.1 on 2018-08-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whizzdiva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdomain',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
